import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin} from 'react-icons/ai'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div id='main-content'>
      <Head>
        <title>Ben Rueter Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>BRUETER</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className=' cursor-pointer text-xl'/>
              </li>
              <li><a href="#" className= 'bg-gradient-to-r from-blue-600 to-purple-900 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-purple-900 text-5xl font-medium'>Ben Rueter</h2>
            <h3 className='text-2xl py-4'>Software developer.</h3>
            <p>Recent computer science graduate looking to get their start in the software industry. Find my contact info below and lets start a conversation.</p>
          </div>
          <div>
            <a href='https://www.linkedin.com/in/brueter'><AiFillLinkedin/></a>
          </div>
        </section>
      </main>
    </div>
  );
}